# Clashé…ç½®æ–‡ä»¶
# ç”Ÿæˆæ—¶é—´: 2025-08-04 08:48:05
# èŠ‚ç‚¹æ•°é‡: 30
# å¹³å‡å»¶è¿Ÿ: 50.4ms

port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  - 8.8.8.8
  fallback:
  - tls://1.1.1.1:853
  - tls://8.8.4.4:853
proxies:
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  server: 45.149.12.25
  port: 8880
  type: vmess
  uuid: 3e1e3e7f-2683-3f36-83b1-1850790295df
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  server: 14.102.228.172
  port: 8880
  type: vmess
  uuid: 70df7c1e-12c8-325f-a12a-34aa46949e60
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 6
  server: 185.251.81.17
  port: 8880
  type: vmess
  uuid: 82cfee4e-e05a-3866-af4d-d09a90506148
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 9
  server: 14.102.229.172
  port: 8880
  type: vmess
  uuid: 70df7c1e-12c8-325f-a12a-34aa46949e60
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 12
  server: 159.242.242.9
  port: 8880
  type: vmess
  uuid: 70df7c1e-12c8-325f-a12a-34aa46949e60
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 13
  server: 104.21.63.135
  port: 443
  type: trojan
  password: fa050497-fc2a-45ee-89c0-96670c4ecb65
  skip-cert-verify: true
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 14
  server: 63.141.128.25
  port: 8880
  type: vmess
  uuid: 3e1e3e7f-2683-3f36-83b1-1850790295df
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 15
  server: 185.251.83.9
  port: 8880
  type: vmess
  uuid: 70df7c1e-12c8-325f-a12a-34aa46949e60
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 16
  server: 5.182.84.172
  port: 8880
  type: vmess
  uuid: 70df7c1e-12c8-325f-a12a-34aa46949e60
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 17
  server: 172.67.170.147
  port: 443
  type: vmess
  uuid: ffcf7ec1-3e09-4821-b3d9-b426a107b73b
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /4Bp70NdrJV3xr1D40NK
  ws-headers:
    Host: xcvfgt6.999854.xyz
  udp: true
- name: HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  server: 103.116.7.241
  port: 8880
  type: vmess
  uuid: 248be52b-35d9-34cb-9b73-e12b78bc1301
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai.in
  ws-headers:
    Host: TG.WangCai2.s2.db-link02.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 18
  server: 172.67.220.32
  port: 443
  type: trojan
  password: ffcf7ec1-3e09-4821-b3d9-b426a107b73b
  skip-cert-verify: true
  udp: true
- name: GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  server: 45.85.119.190
  port: 443
  type: vmess
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /us.kkp.me.eu.org/aa
  ws-headers:
    Host: farid.1.berozha.ir
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 19
  server: 108.165.216.241
  port: 8880
  type: vmess
  uuid: 248be52b-35d9-34cb-9b73-e12b78bc1301
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai.in
  ws-headers:
    Host: TG.WangCai2.s2.db-link02.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 22
  server: 103.160.204.241
  port: 8880
  type: vmess
  uuid: 248be52b-35d9-34cb-9b73-e12b78bc1301
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai.in
  ws-headers:
    Host: TG.WangCai2.s2.db-link02.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 23
  server: 89.116.250.7
  port: 8880
  type: vmess
  uuid: 2d86bf09-0810-3c29-a74c-ba7150848cff
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 24
  server: 141.11.203.26
  port: 8880
  type: vmess
  uuid: 1fcb582e-7ffb-3708-8a0f-96c2a070e40d
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 25
  server: 188.164.248.7
  port: 8880
  type: vmess
  uuid: 2d86bf09-0810-3c29-a74c-ba7150848cff
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 26
  server: 66.235.200.25
  port: 8880
  type: vmess
  uuid: 3e1e3e7f-2683-3f36-83b1-1850790295df
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  server: 46.202.30.25
  port: 8880
  type: vmess
  uuid: 3e1e3e7f-2683-3f36-83b1-1850790295df
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 28
  server: 77.105.163.25
  port: 8880
  type: vmess
  uuid: 3e1e3e7f-2683-3f36-83b1-1850790295df
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  server: 156.238.19.9
  port: 8880
  type: vmess
  uuid: 70df7c1e-12c8-325f-a12a-34aa46949e60
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s4.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 10
  server: 195.85.59.241
  port: 8880
  type: vmess
  uuid: 248be52b-35d9-34cb-9b73-e12b78bc1301
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai.in
  ws-headers:
    Host: TG.WangCai2.s2.db-link02.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  server: 45.153.7.25
  port: 8880
  type: vmess
  uuid: 3e1e3e7f-2683-3f36-83b1-1850790295df
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /dabai&TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  ws-headers:
    Host: TG.WangCai2.s2.cn-db.top
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 20
  server: JJJjjjjjmMMmM.4444926.XYZ
  port: 443
  type: vmess
  uuid: dc50eb1d-244d-4711-b168-a101a5e6fb1b
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /awmqq79B17rfnpXiNaWb
  ws-headers:
    Host: JJJjjjjjmMMmM.4444926.XYZ
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  server: www.visa.com.sg
  port: 8443
  type: vmess
  uuid: 62a00edc-9867-4c66-82ee-d57c19facad3
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /
  ws-headers:
    Host: nurse-boston-queen-romantic.trycloudflare.com
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 27
  server: dddfffvvbnhju.931.pp.ua
  port: 443
  type: vmess
  uuid: a4e8ec0a-75d0-4fc5-837a-4973ed3a9d3e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /14Fziqw1hYgCXNutkS5H
  ws-headers:
    Host: dddfffvvbnhju.931.pp.ua
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 7
  server: sSsdCVfBGNjkI.931.PP.Ua
  port: 443
  type: vmess
  uuid: a4e8ec0a-75d0-4fc5-837a-4973ed3a9d3e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /14Fziqw1hYgCXNutkS5H
  ws-headers:
    Host: sSsdCVfBGNjkI.931.PP.Ua
  udp: true
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 8
  server: 103.185.249.183
  port: 18479
  type: vmess
  uuid: 1479ce84-0de2-477b-ecf7-89b4fbfe8e3f
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  udp: true
  network: tcp
- name: USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 11
  server: tTtTttTttGgGGHHhnMk.iraN2035.DPDNS.ORG
  port: 443
  type: vmess
  uuid: a94fafdb-10d6-46c2-be8a-5c2e8358fbb0
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /CjJ9A46ZRHvgWvVcmjyiKVby2Lp
  ws-headers:
    Host: tttttttttgggghhhnmk.iran2035.dpdns.org
  udp: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ”¯ æ•…éšœè½¬ç§»
  - ğŸ”® è´Ÿè½½å‡è¡¡
  - DIRECT
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 6
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 9
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 12
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 13
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 14
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 15
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 16
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 17
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 18
  - GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 19
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 22
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 23
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 24
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 25
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 26
  - ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 28
  - JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 10
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 20
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 27
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 7
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 8
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 11
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 6
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 9
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 12
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 13
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 14
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 15
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 16
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 17
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 18
  - GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 19
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 22
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 23
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 24
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 25
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 26
  - ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 28
  - JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 10
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 20
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 27
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 7
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 8
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 11
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: ğŸ”¯ æ•…éšœè½¬ç§»
  type: fallback
  proxies:
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 6
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 9
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 12
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 13
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 14
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 15
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 16
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 17
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 18
  - GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 19
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 22
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 23
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 24
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 25
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 26
  - ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 28
  - JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 10
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 20
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 27
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 7
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 8
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 11
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: ğŸ”® è´Ÿè½½å‡è¡¡
  type: load-balance
  proxies:
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 4
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 5
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 6
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 9
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 12
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 13
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 14
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 15
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 16
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 17
  - HKé¦™æ¸¯(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 18
  - GBè‹±å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 19
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 22
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 23
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 24
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 25
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 26
  - ä¹Œå…‹å…°(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 28
  - JPæ—¥æœ¬(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«)
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 10
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 3
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 20
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 2
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 27
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 7
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 8
  - USç¾å›½(mibei77.com ç±³è´èŠ‚ç‚¹åˆ†äº«) 11
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
